#!/bin/sh

if [ ! -e /var/run/upstream ] ; then
  mkdir /var/run/upstream
fi

if [ ! -e /etc/upstream ] ; then
  mkdir /etc/upstream
fi

if [ ! -e /etc/upstream.d ] ; then
  mkdir /etc/upstream.d
fi

if [ ! -e /etc/upstream/resolv.conf ] ; then
  touch /etc/upstream/resolv.conf
fi

chown pihole:pihole -R /var/run/upstream /etc/upstream /etc/upstream.d
chmod 750 /var/run/upstream /etc/upstream /etc/upstream.d
