#!/bin/bash

DNS_ARR=(8.8.8.8 8.8.4.4)
if [ -z "${PIHOLE_DNS_}" ]; then
    if [ -n "${DNS1}" ] ; then
      DNS_ARR=( "$DNS1" )
    fi

    if [[ -n "${DNS2}" && "${DNS2}" != "no" ]] ; then
      DNS_ARR+=( "$DNS2" )
    fi
else
  DNS_ARR=(${PIHOLE_DNS_//;/ })
fi

echo -n "" > /etc/upstream/resolv.conf
for d in ${DNS_ARR[@]} ; do
  echo "nameserver $d" >> /etc/upstream/resolv.conf
done
