#!/bin/sh

sed -i 's/PIHOLE_DNS_1=.*/PIHOLE_DNS_1=127.0.0.1#5300/' /etc/pihole/setupVars.conf
sed -i '/DNS_BOGUS_PRIV=false/d' /etct/pihole/setupVars.conf
sed -i '/PIHOLE_DNS_2=.*/d' /etc/pihole/setupVars.conf
sed -i '/server=.*/d' /etc/dnsmasq.d/01-pihole.conf
sed -i '/bogus-priv/d' /etc/dnsmasq.d/01-pihole.conf

echo "server=127.0.0.1#5300" >> /etc/dnsmasq.d/01-pihole.conf
